spring.application.name=API-GATEWAY

server.port=8080

####################################################
# Eureka Configuration
####################################################

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

####################################################
# CORS Configuration
####################################################

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

####################################################
# AUTH SERVICE
####################################################

spring.cloud.gateway.routes[0].id=AUTH-ROUTE
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=USER-ROUTE
spring.cloud.gateway.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[2].id=VENDOR-ROUTE
spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/vendor/**

spring.cloud.gateway.routes[3].id=ROLE-ROUTE
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/role/**

####################################################
# INVENTORY SERVICE
####################################################

spring.cloud.gateway.routes[4].id=INVENTORY-ROUTE
spring.cloud.gateway.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/inventory/**