spring.application.name=API-GATEWAY

server.port=8080

####################################################
# Eureka Configuration
####################################################

eureka.client.service-url.defaultZone=${EUREKA_URL:http://demo:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

####################################################
# CORS Configuration
####################################################

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://3.110.167.3
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

####################################################
# AUTH SERVICE
####################################################
##   locahost/auth-service /add
spring.cloud.gateway.routes[0].id=AUTH-ROUTE
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=USER-ROUTE
spring.cloud.gateway.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**

spring.cloud.gateway.routes[2].id=VENDOR-ROUTE
spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/vendor/**

spring.cloud.gateway.routes[3].id=ROLE-ROUTE
spring.cloud.gateway.routes[3].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/role/**

####################################################
# INVENTORY SERVICE
####################################################

spring.cloud.gateway.routes[4].id=INVENTORY-ROUTE
spring.cloud.gateway.routes[4].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/inventory/**

####################################################
# PRODUCTION SERVICE
####################################################

spring.cloud.gateway.routes[5].id=PRODUCTION-ROUTE
spring.cloud.gateway.routes[5].uri=lb://PRODUCTION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/production/**

####################################################
# DISPATCH SERVICE
####################################################

spring.cloud.gateway.routes[6].id=DISPATCH-ROUTE
spring.cloud.gateway.routes[6].uri=lb://DISPATCH-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/dispatch/**

####################################################
# BUYER SERVICE
####################################################

spring.cloud.gateway.routes[7].id=BUYER-ROUTE
spring.cloud.gateway.routes[7].uri=lb://BUYER-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/buyer/**

spring.cloud.gateway.routes[8].id=BUYER-ORDER-ROUTE
spring.cloud.gateway.routes[8].uri=lb://BUYER-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/buyer-order/**